FROM tensorflow/tensorflow:2.1.0-gpu-py3 AS base

LABEL stack=clouddose
RUN apt update && apt install -y git     && \
    python -m pip install --upgrade pip  && \
    rm -rf /var/apt/sources*

COPY ./requirements.txt /requirements.txt
RUN python -m pip install -r /requirements.txt

WORKDIR /src
COPY dosecalc/webapi /src/webapi
COPY mcdose/mcdose /src/mcdose
