// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: detection.protobuf

#ifndef PROTOBUF_detection_2eprotobuf__INCLUDED
#define PROTOBUF_detection_2eprotobuf__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace detection {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_detection_2eprotobuf();
void protobuf_AssignDesc_detection_2eprotobuf();
void protobuf_ShutdownFile_detection_2eprotobuf();

class pbDetectedEvents;
class pbDetectionEvent;

// ===================================================================

class pbDetectionEvent : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:detection.pbDetectionEvent) */ {
 public:
  pbDetectionEvent();
  virtual ~pbDetectionEvent();

  pbDetectionEvent(const pbDetectionEvent& from);

  inline pbDetectionEvent& operator=(const pbDetectionEvent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const pbDetectionEvent& default_instance();

  void Swap(pbDetectionEvent* other);

  // implements Message ----------------------------------------------

  inline pbDetectionEvent* New() const { return New(NULL); }

  pbDetectionEvent* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const pbDetectionEvent& from);
  void MergeFrom(const pbDetectionEvent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(pbDetectionEvent* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double globalTime = 1;
  bool has_globaltime() const;
  void clear_globaltime();
  static const int kGlobalTimeFieldNumber = 1;
  double globaltime() const;
  void set_globaltime(double value);

  // required int32 eventId = 2;
  bool has_eventid() const;
  void clear_eventid();
  static const int kEventIdFieldNumber = 2;
  ::google::protobuf::int32 eventid() const;
  void set_eventid(::google::protobuf::int32 value);

  // required int32 detectorId = 3;
  bool has_detectorid() const;
  void clear_detectorid();
  static const int kDetectorIdFieldNumber = 3;
  ::google::protobuf::int32 detectorid() const;
  void set_detectorid(::google::protobuf::int32 value);

  // required double energy = 4;
  bool has_energy() const;
  void clear_energy();
  static const int kEnergyFieldNumber = 4;
  double energy() const;
  void set_energy(double value);

  // @@protoc_insertion_point(class_scope:detection.pbDetectionEvent)
 private:
  inline void set_has_globaltime();
  inline void clear_has_globaltime();
  inline void set_has_eventid();
  inline void clear_has_eventid();
  inline void set_has_detectorid();
  inline void clear_has_detectorid();
  inline void set_has_energy();
  inline void clear_has_energy();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double globaltime_;
  ::google::protobuf::int32 eventid_;
  ::google::protobuf::int32 detectorid_;
  double energy_;
  friend void  protobuf_AddDesc_detection_2eprotobuf();
  friend void protobuf_AssignDesc_detection_2eprotobuf();
  friend void protobuf_ShutdownFile_detection_2eprotobuf();

  void InitAsDefaultInstance();
  static pbDetectionEvent* default_instance_;
};
// -------------------------------------------------------------------

class pbDetectedEvents : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:detection.pbDetectedEvents) */ {
 public:
  pbDetectedEvents();
  virtual ~pbDetectedEvents();

  pbDetectedEvents(const pbDetectedEvents& from);

  inline pbDetectedEvents& operator=(const pbDetectedEvents& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const pbDetectedEvents& default_instance();

  void Swap(pbDetectedEvents* other);

  // implements Message ----------------------------------------------

  inline pbDetectedEvents* New() const { return New(NULL); }

  pbDetectedEvents* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const pbDetectedEvents& from);
  void MergeFrom(const pbDetectedEvents& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(pbDetectedEvents* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .detection.pbDetectionEvent detectionEvent = 1;
  int detectionevent_size() const;
  void clear_detectionevent();
  static const int kDetectionEventFieldNumber = 1;
  const ::detection::pbDetectionEvent& detectionevent(int index) const;
  ::detection::pbDetectionEvent* mutable_detectionevent(int index);
  ::detection::pbDetectionEvent* add_detectionevent();
  ::google::protobuf::RepeatedPtrField< ::detection::pbDetectionEvent >*
      mutable_detectionevent();
  const ::google::protobuf::RepeatedPtrField< ::detection::pbDetectionEvent >&
      detectionevent() const;

  // @@protoc_insertion_point(class_scope:detection.pbDetectedEvents)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::detection::pbDetectionEvent > detectionevent_;
  friend void  protobuf_AddDesc_detection_2eprotobuf();
  friend void protobuf_AssignDesc_detection_2eprotobuf();
  friend void protobuf_ShutdownFile_detection_2eprotobuf();

  void InitAsDefaultInstance();
  static pbDetectedEvents* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// pbDetectionEvent

// required double globalTime = 1;
inline bool pbDetectionEvent::has_globaltime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void pbDetectionEvent::set_has_globaltime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void pbDetectionEvent::clear_has_globaltime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void pbDetectionEvent::clear_globaltime() {
  globaltime_ = 0;
  clear_has_globaltime();
}
inline double pbDetectionEvent::globaltime() const {
  // @@protoc_insertion_point(field_get:detection.pbDetectionEvent.globalTime)
  return globaltime_;
}
inline void pbDetectionEvent::set_globaltime(double value) {
  set_has_globaltime();
  globaltime_ = value;
  // @@protoc_insertion_point(field_set:detection.pbDetectionEvent.globalTime)
}

// required int32 eventId = 2;
inline bool pbDetectionEvent::has_eventid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void pbDetectionEvent::set_has_eventid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void pbDetectionEvent::clear_has_eventid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void pbDetectionEvent::clear_eventid() {
  eventid_ = 0;
  clear_has_eventid();
}
inline ::google::protobuf::int32 pbDetectionEvent::eventid() const {
  // @@protoc_insertion_point(field_get:detection.pbDetectionEvent.eventId)
  return eventid_;
}
inline void pbDetectionEvent::set_eventid(::google::protobuf::int32 value) {
  set_has_eventid();
  eventid_ = value;
  // @@protoc_insertion_point(field_set:detection.pbDetectionEvent.eventId)
}

// required int32 detectorId = 3;
inline bool pbDetectionEvent::has_detectorid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void pbDetectionEvent::set_has_detectorid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void pbDetectionEvent::clear_has_detectorid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void pbDetectionEvent::clear_detectorid() {
  detectorid_ = 0;
  clear_has_detectorid();
}
inline ::google::protobuf::int32 pbDetectionEvent::detectorid() const {
  // @@protoc_insertion_point(field_get:detection.pbDetectionEvent.detectorId)
  return detectorid_;
}
inline void pbDetectionEvent::set_detectorid(::google::protobuf::int32 value) {
  set_has_detectorid();
  detectorid_ = value;
  // @@protoc_insertion_point(field_set:detection.pbDetectionEvent.detectorId)
}

// required double energy = 4;
inline bool pbDetectionEvent::has_energy() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void pbDetectionEvent::set_has_energy() {
  _has_bits_[0] |= 0x00000008u;
}
inline void pbDetectionEvent::clear_has_energy() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void pbDetectionEvent::clear_energy() {
  energy_ = 0;
  clear_has_energy();
}
inline double pbDetectionEvent::energy() const {
  // @@protoc_insertion_point(field_get:detection.pbDetectionEvent.energy)
  return energy_;
}
inline void pbDetectionEvent::set_energy(double value) {
  set_has_energy();
  energy_ = value;
  // @@protoc_insertion_point(field_set:detection.pbDetectionEvent.energy)
}

// -------------------------------------------------------------------

// pbDetectedEvents

// repeated .detection.pbDetectionEvent detectionEvent = 1;
inline int pbDetectedEvents::detectionevent_size() const {
  return detectionevent_.size();
}
inline void pbDetectedEvents::clear_detectionevent() {
  detectionevent_.Clear();
}
inline const ::detection::pbDetectionEvent& pbDetectedEvents::detectionevent(int index) const {
  // @@protoc_insertion_point(field_get:detection.pbDetectedEvents.detectionEvent)
  return detectionevent_.Get(index);
}
inline ::detection::pbDetectionEvent* pbDetectedEvents::mutable_detectionevent(int index) {
  // @@protoc_insertion_point(field_mutable:detection.pbDetectedEvents.detectionEvent)
  return detectionevent_.Mutable(index);
}
inline ::detection::pbDetectionEvent* pbDetectedEvents::add_detectionevent() {
  // @@protoc_insertion_point(field_add:detection.pbDetectedEvents.detectionEvent)
  return detectionevent_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::detection::pbDetectionEvent >*
pbDetectedEvents::mutable_detectionevent() {
  // @@protoc_insertion_point(field_mutable_list:detection.pbDetectedEvents.detectionEvent)
  return &detectionevent_;
}
inline const ::google::protobuf::RepeatedPtrField< ::detection::pbDetectionEvent >&
pbDetectedEvents::detectionevent() const {
  // @@protoc_insertion_point(field_list:detection.pbDetectedEvents.detectionEvent)
  return detectionevent_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace detection

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_detection_2eprotobuf__INCLUDED
