# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detection.protobuf

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='detection.protobuf',
  package='detection',
  syntax='proto2',
  serialized_pb=_b('\n\x12\x64\x65tection.protobuf\x12\tdetection\"[\n\x10pbDetectionEvent\x12\x12\n\nglobalTime\x18\x01 \x02(\x01\x12\x0f\n\x07\x65ventId\x18\x02 \x02(\x05\x12\x12\n\ndetectorId\x18\x03 \x02(\x05\x12\x0e\n\x06\x65nergy\x18\x04 \x02(\x01\"G\n\x10pbDetectedEvents\x12\x33\n\x0e\x64\x65tectionEvent\x18\x01 \x03(\x0b\x32\x1b.detection.pbDetectionEvent')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBDETECTIONEVENT = _descriptor.Descriptor(
  name='pbDetectionEvent',
  full_name='detection.pbDetectionEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='globalTime', full_name='detection.pbDetectionEvent.globalTime', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eventId', full_name='detection.pbDetectionEvent.eventId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='detectorId', full_name='detection.pbDetectionEvent.detectorId', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='energy', full_name='detection.pbDetectionEvent.energy', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=124,
)


_PBDETECTEDEVENTS = _descriptor.Descriptor(
  name='pbDetectedEvents',
  full_name='detection.pbDetectedEvents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detectionEvent', full_name='detection.pbDetectedEvents.detectionEvent', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=197,
)

_PBDETECTEDEVENTS.fields_by_name['detectionEvent'].message_type = _PBDETECTIONEVENT
DESCRIPTOR.message_types_by_name['pbDetectionEvent'] = _PBDETECTIONEVENT
DESCRIPTOR.message_types_by_name['pbDetectedEvents'] = _PBDETECTEDEVENTS

pbDetectionEvent = _reflection.GeneratedProtocolMessageType('pbDetectionEvent', (_message.Message,), dict(
  DESCRIPTOR = _PBDETECTIONEVENT,
  __module__ = 'detection.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:detection.pbDetectionEvent)
  ))
_sym_db.RegisterMessage(pbDetectionEvent)

pbDetectedEvents = _reflection.GeneratedProtocolMessageType('pbDetectedEvents', (_message.Message,), dict(
  DESCRIPTOR = _PBDETECTEDEVENTS,
  __module__ = 'detection.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:detection.pbDetectedEvents)
  ))
_sym_db.RegisterMessage(pbDetectedEvents)


# @@protoc_insertion_point(module_scope)
